version: '3'
services:
  app:
    build: ./php
    container_name: app
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - data_base:/var/lib/mysql
      - ./initSQL:/docker-entrypoint-initdb.d
volumes:
  data_base:
